In [1]:
# Importando as bibliotecas essenciais
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt # Para visualização (opcional, mas recomendado)
from sklearn.tree import plot_tree # Para visualizar a árvore (muito legal para a aula!)


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/carara/.local/lib/python3.10/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/home/carara/.local/lib/python3.10/site-packages/traitlets/config/application.py", line 1082, in launch_instance
    app.start()
  File "/home/carara/.local/lib/python3.10/site-pac

AttributeError: _ARRAY_API not found

In [2]:
# Carregando o dataset Iris
iris = load_iris()

# As features (características) das flores
# X são as 'entradas' para o nosso modelo
X = iris.data

# O target (alvo) ou rótulos, que são as espécies das flores (0, 1, 2)
# y são as 'saídas' ou 'respostas' que queremos que o modelo aprenda a prever
y = iris.target

# Podemos ver os nomes das features (atributos)
print("Nomes das Features:", iris.feature_names)

# E os nomes das classes (espécies), que correspondem a 0, 1, 2
print("Nomes das Classes (Target):", iris.target_names)

# Visualizando as primeiras 5 linhas das features (X) e do target (y)
print("\nPrimeiras 5 linhas das Features (X):\n", X[:5])
print("\nPrimeiras 5 linhas do Target (y):\n", y[:5])

Nomes das Features: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Nomes das Classes (Target): ['setosa' 'versicolor' 'virginica']

Primeiras 5 linhas das Features (X):
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

Primeiras 5 linhas do Target (y):
 [0 0 0 0 0]


In [3]:
# Dividindo os dados em conjuntos de treino e teste
# test_size=0.3 significa que 30% dos dados serão usados para testar o modelo
# random_state=42 garante que a divisão dos dados seja sempre a mesma, tornando seus resultados reproduzíveis.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print(f"\nTamanho do conjunto de treino (X_train): {X_train.shape[0]} amostras")
print(f"Tamanho do conjunto de teste (X_test): {X_test.shape[0]} amostras")


Tamanho do conjunto de treino (X_train): 105 amostras
Tamanho do conjunto de teste (X_test): 45 amostras


In [4]:
# Escolhendo o algoritmo: Árvore de Decisão para Classificação
# random_state também ajuda na reprodutibilidade da própria árvore (sua estrutura)
model = DecisionTreeClassifier(random_state=42)

In [5]:
# Treinando o modelo com os dados de treino
# O método .fit() é onde o modelo 'aprende' os padrões nos dados.
# Ele recebe as features de treino (X_train) e os rótulos corretos (y_train).
model.fit(X_train, y_train)

print("\nModelo treinado com sucesso!")


Modelo treinado com sucesso!


In [6]:
# Fazendo previsões nos dados de teste (dados que o modelo nunca viu antes)
# O método .predict() usa o que o modelo aprendeu para tentar adivinhar os rótulos.
predictions = model.predict(X_test)

print("\nAlgumas previsões do modelo no conjunto de teste:")
# Mostrar as primeiras 10 previsões e os valores reais correspondentes
for i in range(10):
    predicted_species = iris.target_names[predictions[i]]
    actual_species = iris.target_names[y_test[i]]
    print(f"Flor {i+1}: Previsão: {predicted_species}, Real: {actual_species}")


Algumas previsões do modelo no conjunto de teste:
Flor 1: Previsão: versicolor, Real: versicolor
Flor 2: Previsão: setosa, Real: setosa
Flor 3: Previsão: virginica, Real: virginica
Flor 4: Previsão: versicolor, Real: versicolor
Flor 5: Previsão: versicolor, Real: versicolor
Flor 6: Previsão: setosa, Real: setosa
Flor 7: Previsão: versicolor, Real: versicolor
Flor 8: Previsão: virginica, Real: virginica
Flor 9: Previsão: versicolor, Real: versicolor
Flor 10: Previsão: versicolor, Real: versicolor


In [7]:
# Avaliando o desempenho do modelo usando a acurácia no conjunto de TESTE
test_accuracy = accuracy_score(y_test, predictions)

# Calculando a acurácia no conjunto de TREINO para verificar overfitting
train_predictions = model.predict(X_train)
train_accuracy = accuracy_score(y_train, train_predictions)

print(f"\n--- Avaliação do Modelo ---")
print(f"Acurácia do modelo no conjunto de TREINO: {train_accuracy:.2f}")
print(f"Acurácia do modelo no conjunto de TESTE: {test_accuracy:.2f}")

# Discussão sobre Overfitting:
if train_accuracy > test_accuracy + 0.01: # Adicionar uma pequena tolerância para variação
    print("\n **Alerta de Overfitting!**")
    print("Percebam que a acurácia no **treino** é 1.00 (ou muito alta), mas no **teste** é um pouco menor.")
    print("Isso significa que o modelo pode ter 'decorado' os dados de treino, incluindo o 'ruído' ou detalhes específicos, em vez de aprender os padrões gerais.")
    print("É como um aluno que decora a apostila e tira 100 na prova, mas não consegue resolver problemas novos fora da apostila.")
    print("Árvores de Decisão sem restrições são propensas a isso, pois tentam classificar perfeitamente cada exemplo de treino.")
else:
    print("\nPara este dataset simples, o modelo parece estar generalizando bem ou o overfitting é mínimo.")
    print("Em datasets mais complexos, o overfitting é um desafio muito comum.")

"""
Como lidar com o Overfitting (Árvores de Decisão)?
Podemos limitar o crescimento da árvore, o que é uma forma de 'poda'.
Isso é feito usando hiperparâmetros como:
- `max_depth`: Define a profundidade máxima que a árvore pode ter;
- `min_samples_leaf`: O número mínimo de amostras que deve haver em um nó folha;
Vamos refazer o treinamento com um `max_depth` limitado para ver o efeito.
"""

# Exemplo de modelo com max_depth limitado para combater overfitting
model_pruned = DecisionTreeClassifier(max_depth=3, random_state=42) # Experimente com 2, 3 ou 4
model_pruned.fit(X_train, y_train)

train_predictions_pruned = model_pruned.predict(X_train)
test_predictions_pruned = model_pruned.predict(X_test)

train_accuracy_pruned = accuracy_score(y_train, train_predictions_pruned)
test_accuracy_pruned = accuracy_score(y_test, test_predictions_pruned)

print(f"\n--- Modelo com max_depth={model_pruned.max_depth} ---")
print(f"Acurácia de TREINO (modelo podado): {train_accuracy_pruned:.2f}")
print(f"Acurácia de TESTE (modelo podado): {test_accuracy_pruned:.2f}")

if train_accuracy_pruned > test_accuracy_pruned + 0.01:
    print("Mesmo com max_depth, pode haver uma pequena diferença, mas a árvore é mais simples.")
else:
    print("Percebam como, ao limitar a profundidade, a diferença entre a acurácia de treino e teste diminuiu, indicando que o modelo generaliza melhor.")

#Para aprofundar no combate ao overfitting, pesquisem  sobre Validação Cruzada, Random Forest e Gradient Boosting!


--- Avaliação do Modelo ---
Acurácia do modelo no conjunto de TREINO: 1.00
Acurácia do modelo no conjunto de TESTE: 1.00

Para este dataset simples, o modelo parece estar generalizando bem ou o overfitting é mínimo.
Em datasets mais complexos, o overfitting é um desafio muito comum.

--- Modelo com max_depth=3 ---
Acurácia de TREINO (modelo podado): 0.95
Acurácia de TESTE (modelo podado): 1.00
Percebam como, ao limitar a profundidade, a diferença entre a acurácia de treino e teste diminuiu, indicando que o modelo generaliza melhor.


In [8]:
#Comparação com outros modelos de classificação

print("--- Comparando Diferentes Modelos de Classificação ---")
print("Vamos treinar e avaliar alguns dos algoritmos de classificação mais comuns:")

# Importar os algoritmos adicionais
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB # Gaussian Naive Bayes para dados contínuos
from sklearn.svm import SVC # Support Vector Classifier (SVM para classificação)
from sklearn.tree import DecisionTreeClassifier # Já importado

# Dicionário para armazenar os modelos e suas acurácias
models = {
    "Árvore de Decisão (max_depth=3)": DecisionTreeClassifier(max_depth=3, random_state=42),
    "K-Nearest Neighbors (k=5)": KNeighborsClassifier(n_neighbors=5),
    "Regressão Logística": LogisticRegression(random_state=42, max_iter=200), # max_iter para garantir convergência
    "Análise Discriminante Linear (LDA)": LinearDiscriminantAnalysis(),
    "Naive Bayes (Gaussiano)": GaussianNB(),
    "Support Vector Machine (SVM)": SVC(random_state=42) # Kernel padrão 'rbf' é bom para começar
}

results = {}

# Iterar sobre os modelos, treinar e avaliar
for name, model in models.items():
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    accuracy = accuracy_score(y_test, predictions)
    results[name] = accuracy

print("\n--- Resumo dos Resultados ---")
for name, accuracy in results.items():
    print(f"- {name}: {accuracy:.2f}")

"""
Conclusão da Comparação:
Percebam como diferentes algoritmos podem ter desempenhos parecidos ou diferentes no mesmo problema, mesmo com os mesmos dados.
A escolha do melhor modelo depende de vários fatores, como o problema em questão, as características dos dados (ex: linearidade, separabilidade), e até mesmo a interpretabilidade que precisamos do modelo.
Não existe um algoritmo 'bala de prata' que sirva para tudo! A prática é experimentar e comparar.
Essa é apenas uma amostra; existem muitos outros algoritmos e técnicas avançadas para explorar!
"""

--- Comparando Diferentes Modelos de Classificação ---
Vamos treinar e avaliar alguns dos algoritmos de classificação mais comuns:

--- Resumo dos Resultados ---
- Árvore de Decisão (max_depth=3): 1.00
- K-Nearest Neighbors (k=5): 1.00
- Regressão Logística: 1.00
- Análise Discriminante Linear (LDA): 1.00
- Naive Bayes (Gaussiano): 0.98
- Support Vector Machine (SVM): 1.00


"\nConclusão da Comparação:\nPercebam como diferentes algoritmos podem ter desempenhos parecidos ou diferentes no mesmo problema, mesmo com os mesmos dados.\nA escolha do melhor modelo depende de vários fatores, como o problema em questão, as características dos dados (ex: linearidade, separabilidade), e até mesmo a interpretabilidade que precisamos do modelo.\nNão existe um algoritmo 'bala de prata' que sirva para tudo! A prática é experimentar e comparar.\nEssa é apenas uma amostra; existem muitos outros algoritmos e técnicas avançadas para explorar!\n"